# fly.toml app configuration file generated for zane-ebook on 2023-10-19T14:29:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zane-ebook"
primary_region = "atl"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
