# frozen_string_literal: true

source "https://rubygems.org"


gem "sinatra"
gem "sinatra-contrib"
gem "redcarpet"
gem "erubis"
gem "minitest"
gem "rack-test"
gem "bcrypt"

ruby "3.2.2"



# gem "rails"
